# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Greg Nemetz
description: "Hi I'm Greg, and I'm a Data Analyst. My portfolio focuses on interesting projects I've recently undertaken. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Dublin, OH"
resume_url: /img/Greg_Nemetz%20_Resume.pdf
avatar_image: /img/Profile_Pic_%20v1.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/greg-nemetz?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bspg4ldfzRE2hDYr4lAJVZQ%3D%3D" # Add your linkedln handle
github: "https://github.com/gnemetz"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

